### ISSUE TITLE
Python 3.8: AttributeError: 'ASTTranslator' object has no attribute '_translate_constant'

### ISSUE THREAD

**Issue by rix0rrr** [alehander42/pseudo-python#15]
Getting the above error when running the latest `pseudo-python` on the `fib.py` example:

```
$ pseudo-python original.py

Traceback (most recent call last):
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/bin/pseudo-python", line 33, in <module>
    sys.exit(load_entry_point('pseudo-python==0.2.34', 'console_scripts', 'pseudo-python')())
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/main.py", line 45, in main
    clj = pseudo_python.translate_to_yaml(source)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/__init__.py", line 10, in translate_to_yaml
    return yaml.dump(translate(source))
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/__init__.py", line 6, in translate
    return pseudo_python.ast_translator.ASTTranslator(pseudo_python.parser.parse(source), source).translate()
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 106, in translate
    main = self._translate_main()
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 144, in _translate_main
    return self._translate_node(self.main)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 282, in _translate_node
    x = self._translate_node(n)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 278, in _translate_node
    return getattr(self, '_translate_%s' % type(node).__name__.lower())(**fields)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 718, in _translate_expr
    return self._translate_node(value)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 278, in _translate_node
    return getattr(self, '_translate_%s' % type(node).__name__.lower())(**fields)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 486, in _translate_call
    arg_nodes = self._translate_node(args)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 282, in _translate_node
    x = self._translate_node(n)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 278, in _translate_node
    return getattr(self, '_translate_%s' % type(node).__name__.lower())(**fields)
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 489, in _translate_call
    arg_nodes = [arg if not isinstance(arg, ast.AST) else self._translate_node(arg) for arg in args]
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 489, in <listcomp>
    arg_nodes = [arg if not isinstance(arg, ast.AST) else self._translate_node(arg) for arg in args]
  File "/Users/rix0rrr/Dev/transpilation/pseudolang/.env/lib/python3.8/site-packages/pseudo_python/ast_translator.py", line 278, in _translate_node
    return getattr(self, '_translate_%s' % type(node).__name__.lower())(**fields)
AttributeError: 'ASTTranslator' object has no attribute '_translate_constant'
```

**Comment by tomsabanov** [comment]
I'm having the same issue. Are there any solutions to this yet?
