### ISSUE TITLE
Support map and lambda

### ISSUE THREAD

**Issue by jzjsuper** [alehander42/pseudo-python#3]
test.py:
```python
a = map(lambda x: x + 1, [1, 2, 3])
```
When I try to convert `test.py`, the program throws the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pseudo-python", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/main.py", line 61, in main
    node = pseudo_python.translate(source)
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/__init__.py", line 5, in translate
    return pseudo_python.ast_translator.ASTTranslator(pseudo_python.parser.parse(source), source).translate()
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 104, in translate
    main = self._translate_main()
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 142, in _translate_main
    return self._translate_node(self.main)
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 280, in _translate_node
    x = self._translate_node(n)
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 276, in _translate_node
    return getattr(self, '_translate_%s' % type(node).__name__.lower())(**fields)
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 969, in _translate_assign
    value_node = self._translate_node(value)
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 276, in _translate_node
    return getattr(self, '_translate_%s' % type(node).__name__.lower())(**fields)
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 422, in _translate_call
    arg_nodes = [arg if not isinstance(arg, ast.AST) else self._translate_node(arg) for arg in args]
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 422, in <listcomp>
    arg_nodes = [arg if not isinstance(arg, ast.AST) else self._translate_node(arg) for arg in args]
  File "/usr/local/lib/python3.5/site-packages/pseudo_python/ast_translator.py", line 276, in _translate_node
    return getattr(self, '_translate_%s' % type(node).__name__.lower())(**fields)
AttributeError: 'ASTTranslator' object has no attribute '_translate_lambda'
```

**Comment by alehander42** [comment]
`map` and `filter` are currently not supported in Pseudo-Python, and list comprehension usage is encouraged. 
They will be supported in v0.3, but only used like `list(filter)` and `list(map)`. Why?

* List comprehensions are recommended by most python style guides and are generally preferred by the community (I love `map` and `filter` too, but I prefer being consistent with the language philosophy)

* The Python3 semantics of filter and map are different than Python2: they return iterators and they are lazily evaluated. If Pseudo starts supporting lazy evaluation, they will be useful, but currently 
`s = filter(lambda e: 1 / e, [2, 0])` behaves differently compared to `[4, 0].select { |e| 1 / e }`
That's why only the `list()` uses would be valid in v0.3

An attribute error ofc is not ok, that will be fixed today

**Comment by alehander42** [comment]
No need to wait for v0.3, the `list(map)` support is ready
